POST https://artcryption-poc.directus.app/graphql
Content-Type: application/json
Authorization: Bearer kBgJQb-Eqvq71MUJdzDn65xUfIFzcCDx
X-REQUEST-TYPE: GraphQL

query {
  Products {
    title
  }
}


###

POST https://artcryption-poc.directus.app/flows/trigger/902dc52a-2fb8-4b65-bc4e-c6804b5b101f
Content-Type: application/json

{
  "name": "test",
  "email": "reg@usul.su"
}