POST https://artcryption-poc.directus.app/graphql
Content-Type: application/json
Authorization: Bearer kBgJQb-Eqvq71MUJdzDn65xUfIFzcCDx
X-REQUEST-TYPE: GraphQL

query {
  Products {
    title
  }
}


###

POST https://artcryption-poc.directus.app/flows/trigger/902dc52a-2fb8-4b65-bc4e-c6804b5b101f
Content-Type: application/json

{
  "name": "test",
  "email": "reg@usul.su"
}


###

POST https://eox5ge5cp0ztfqf.m.pipedream.net
Content-Type: application/json

{
  "name": "lalalal",
}


###
POST https://hooks.slack.com/actions/T784R3J6R/6158782767664/3Vkg9uxY7NDiXVjOuOQ4EMgf
Content-Type: application/json

{
  "text": "Hello world"
}


###
### POST http://localhost:3000/api/review
POST https://mvp-directus-next-js-14.vercel.app/api/review

{
  "payload": {
  "type": "block_actions",
  "user": {
    "id": "UQKHERRPW",
    "username": "oleg",
    "name": "oleg",
    "team_id": "T784R3J6R"
  },
  "api_app_id": "A063GJMMMCP",
  "token": "5ts1pqoCnu5rEAKjAN2tiaVk",
  "container": {
    "type": "message",
    "message_ts": "1698934668.339599",
    "channel_id": "C063CFBNGCF",
    "is_ephemeral": false
  },
  "trigger_id": "6138242341092.246161120229.da9c9e10b4bf1f376b5eaef92fcc2843",
  "team": { "id": "T784R3J6R", "domain": "gitnation" },
  "enterprise": null,
  "is_enterprise_install": false,
  "channel": { "id": "C063CFBNGCF", "name": "privategroup" },
  "message": {
    "type": "message",
    "subtype": "bot_message",
    "text": "Attention: New Product Submission \ud83d\udea5 We have received *a new product submission* on our website. It is crucial that we review and take action on this submission promptly. Please review the details and either *approve* or *dismiss* the submission. Your swift response is highly appreciated to ensure efficient processing and provide the best user experience. name: Oleg Proskurin title: lalalalalalla description: lalalalalalla undefined oleg@gitnation.org \ud83c\udf4f Approve button \ud83d\ude45 Reject button",
    "ts": "1698934668.339599",
    "bot_id": "B063X2A9VC3",
    "blocks": [
      {
        "type": "header",
        "block_id": "RxWuU",
        "text": {
          "type": "plain_text",
          "text": "Attention: New Product Submission :traffic_light:",
          "emoji": true
        }
      },
      {
        "type": "section",
        "block_id": "nUit4",
        "text": {
          "type": "mrkdwn",
          "text": "We have received *a new product submission* on our website. It is crucial that we review and take action on this submission promptly. Please review the details and either *approve* or *dismiss* the submission. Your swift response is highly appreciated to ensure efficient processing and provide the best user experience.",
          "verbatim": false
        }
      },
      {
        "type": "section",
        "block_id": "Dw7sg",
        "fields": [
          {
            "type": "plain_text",
            "text": "name: Oleg Proskurin",
            "emoji": true
          },
          {
            "type": "plain_text",
            "text": "title: lalalalalalla",
            "emoji": true
          },
          {
            "type": "plain_text",
            "text": "description: lalalalalalla",
            "emoji": true
          },
          { "type": "plain_text", "text": "undefined", "emoji": true },
          { "type": "plain_text", "text": "oleg@gitnation.org", "emoji": true }
        ]
      },
      { "type": "divider", "block_id": "8xGKE" },
      {
        "type": "actions",
        "block_id": "GwsIS",
        "elements": [
          {
            "type": "button",
            "action_id": "TbABr",
            "text": {
              "type": "plain_text",
              "text": ":green_apple: Approve",
              "emoji": true
            },
            "style": "primary",
            "value": "click_me_123"
          },
          {
            "type": "button",
            "action_id": "yT70d",
            "text": {
              "type": "plain_text",
              "text": ":no_good: Reject",
              "emoji": true
            },
            "style": "danger",
            "value": "click_me_123"
          }
        ]
      }
    ]
  },
  "state": { "values": {} },
  "response_url": "https://hooks.slack.com/actions/T784R3J6R/6158782767664/3Vkg9uxY7NDiXVjOuOQ4EMgf",
  "actions": [
    {
      "action_id": "yT70d",
      "block_id": "GwsIS",
      "text": {
        "type": "plain_text",
        "text": ":no_good: Reject",
        "emoji": true
      },
      "value": "{\"first-name\":\"Oleg\",\"last-name\":\"Proskurin\",\"title\":\"lalalalalalla\",\"collection\":\"abstract-art\",\"email\":\"oleg@gitnation.org\",\"country\":\"US\",\"phone-number\":\"234234234234\",\"description\":\"lalalalalalla\"}",
      "style": "danger",
      "type": "button",
      "action_ts": "1698935719.470787"
    }
  ]
}

}